skedule/admin/routes.py
from flask import render_template, send_from_directory, Blueprint, request, flash, abort, redirect, url_for
from flask_login import login_user, current_user, logout_user, login_required
from skedule import db, bcrypt
from skedule.models import User, Day, Shift, Template, Assignment
from skedule.admin.forms import AddTemplateForm, EditTemplateForm, NewWeekScheduleForm, DeleteWeekScheduleForm, EditShiftForm, AddShiftForm, DeleteShiftForm
from skedule.utils import getLocalizedTime, getWeek, getDayName, daysOfCalendarWeek, oneWeekPrior, oneWeekLater, ymdToDateTime, ymdhmToDateTime, addToTime, deepCopyDict

admin = Blueprint('admin', __name__)

@admin.route('/schedule/configure', methods=['GET', 'POST'])
@login_required
def configureSchedule():
	newWeekScheduleForm = NewWeekScheduleForm()
	deleteWeekScheduleForm = DeleteWeekScheduleForm()
	unavail = False
	inputWeekOf = request.args.get('week')
	if inputWeekOf:
		weekOf = ymdToDateTime(inputWeekOf)
		if not weekOf: abort(404)
		calendarWeek = daysOfCalendarWeek(weekOf)
	else:
		calendarWeek = daysOfCalendarWeek(getLocalizedTime())
	weekOf = calendarWeek[0]
	weekdays = [{'name': getDayName(day.weekday()), 'date': day.strftime('%m/%d')} for day in calendarWeek]
	days = []
	for day in calendarWeek:
		dayRow = Day.query.filter_by(date=day.date()).first()
		if dayRow:
			days.append(dayRow)
		else:
			unavail = True

	if newWeekScheduleForm.submitNewWeek.data and newWeekScheduleForm.validate():
		for day in calendarWeek:
			dayRow = Day.query.filter_by(date=day.date()).first()
			if not dayRow:
				newDay = Day(name=day.date().strftime('%m/%d/%Y'), date=day.date())
				db.session.add(newDay)
				db.session.commit()
		flash('Schedule created for the week of '+weekOf.strftime('%B %d, %Y'), 'success')
		return redirect(url_for('admin.configureSchedule', week=weekOf.strftime('%Y-%m-%d')))

	if deleteWeekScheduleForm.submitDeleteWeek.data and deleteWeekScheduleForm.validate():
		for day in calendarWeek:
			dayRow = Day.query.filter_by(date=day.date()).first()
			if dayRow:
				for shift in dayRow.shifts:
					db.session.delete(shift)
				db.session.delete(dayRow)
				db.session.commit()
		flash('Schedule deleted for the week of '+weekOf.strftime('%B %d, %Y'), 'success')
		return redirect(url_for('admin.configureSchedule', week=weekOf.strftime('%Y-%m-%d')))

	return render_template('configure_schedule.html', deleteWeekScheduleForm=deleteWeekScheduleForm,newWeekScheduleForm=newWeekScheduleForm, unavail=unavail, weekdays=weekdays, weekOf=weekOf, days=days, owp=oneWeekPrior(weekOf), owl=oneWeekLater(weekOf), hours=[str(i).zfill(4) for i in range(800, 2400, 100)])

@admin.route('/schedule/configure/add-shift', methods=['GET', 'POST'])
@login_required
def addShift():
	inputDateTime = request.args.get('datetime')
	dateTime = ymdhmToDateTime(inputDateTime)
	if not dateTime: abort(404)
	if not Day.query.filter_by(date=dateTime.date()).first(): abort(404)

	form = AddShiftForm()
	
	if form.validate_on_submit():
		startTime = ymdhmToDateTime(dateTime.strftime('%Y-%m-%d-')+form.startTime.data)
		if not startTime:
			flash('Invalid Start DateTime!', 'danger')
			return redirect(url_for('admin.addShift', datetime=inputDateTime))

		day = Day.query.filter_by(date=dateTime.date()).first()
		shift = Shift(name=form.shiftName.data, startTime=startTime, duration=form.duration.data,
			maxEmployees=form.maxEmployees.data, minEmployees=form.minEmployees.data, day_id=day.id
		)
		db.session.add(shift)
		db.session.commit()
		if form.employees.data:
			empToAdd = form.employees.data.replace(' ', '').split(',')
			for emp in empToAdd:
				if not emp.isdigit():
					flash('Invalid Employee List!', 'danger')
					return redirect(url_for('admin.addShift', datetime=inputDateTime))
				employee = User.query.filter_by(external_id=emp).first()
				if not employee:
					flash(f'Employee "{emp}" not found!', 'danger')
					return redirect(url_for('admin.addShift', datetime=inputDateTime))
				shift.employees.append(employee)
				db.session.commit()

		flash('Shift Added!', 'success')
		return redirect(url_for('admin.configureSchedule', week=dateTime.date()))
	form.startTime.data = dateTime.strftime('%H%M')
	return render_template('add_shift.html', form=form, startDate=dateTime.strftime('%m/%d/%Y'), startTime=form.startTime.data)

@admin.route('/schedule/configure/shift/<int:shift_id>', methods=['GET', 'POST'])
@login_required
def editShift(shift_id):
	shift = Shift.query.get_or_404(shift_id)
	date = shift.day.date
	form = EditShiftForm()
	deleteShiftForm = DeleteShiftForm()

	if request.method == 'GET':
		form.shiftName.data = shift.name
		form.startTime.data = shift.startTime.strftime('%H%M')
		form.duration.data = str(shift.duration).zfill(4)
		form.maxEmployees.data = shift.maxEmployees
		form.minEmployees.data = shift.minEmployees

	if form.validate_on_submit():
		shift.name = form.shiftName.data
		startTime = ymdhmToDateTime(date.strftime('%Y-%m-%d-')+form.startTime.data)
		shift.startTime = startTime
		shift.duration = form.duration.data
		shift.maxEmployees = form.maxEmployees.data
		shift.minEmployees = form.minEmployees.data
		db.session.commit()
		
		flash('Shift Updated!', 'success')
		return redirect(url_for('main.viewShift', shift_id=shift.id))

	return render_template('edit_shift.html', shift=shift, shift_id=shift_id, form=form, deleteShiftForm=deleteShiftForm, startDate=date.strftime('%m/%d/%Y'))

@admin.route('/schedule/configure/shift/<int:shift_id>/delete', methods=['POST'])
@login_required
def deleteShift(shift_id):
	shift = Shift.query.get_or_404(shift_id)
	url = url_for('admin.configureSchedule', week=shift.day.date.strftime('%Y-%m-%d'))
	flash(f'Shift "{shift.name}" Deleted!', 'success')
	db.session.delete(shift)
	db.session.commit()
	
	return redirect(url)

@admin.route('/schedule/configure/add-template', methods=['GET', 'POST'])
@login_required
def templateManager():
	form = AddTemplateForm()
	hour = request.args.get('hour')
	if form.validate_on_submit():
		template = Template(name=form.shiftName.data, startTime=form.startTime.data,
			duration=form.duration.data, minEmployees=form.minEmployees.data, maxEmployees=form.maxEmployees.data)
		db.session.add(template)
		db.session.commit()
		if form.employees.data:
			empToAdd = form.employees.data.replace(' ', '').split(',')
			for emp in empToAdd:
				if not emp.isdigit():
					flash('Invalid Employee List!', 'danger')
					return redirect(url_for('admin.templateManager'))
				employee = User.query.filter_by(external_id=emp).first()
				if not employee:
					flash(f'Employee "{emp}" not found!', 'danger')
					return redirect(url_for('admin.templateManager'))
				template.employees.append(employee)
				db.session.commit()
		flash('Template created', 'success')
		return redirect(url_for('admin.viewTemplates'))
	if hour:
		form.startTime.data = hour
	return render_template('template_manager.html', form=form)

@admin.route('/schedule/configure/templates')
def viewTemplates():
	templates = Template.query.all()
	return render_template('view_templates.html', templates=templates, hours=[str(i).zfill(4) for i in range(800, 2400, 100)])

@admin.route('/schedule/configure/template/<int:template_id>', methods=['GET','POST'])
@login_required
def editTemplate(template_id):
	template = Template.query.get_or_404(template_id)
	form = EditTemplateForm()
	if request.method == 'GET':
		form.shiftName.data = template.name
		form.startTime.data = template.startTime
		form.duration.data = str(template.duration).zfill(4)
		form.maxEmployees.data = template.maxEmployees
		form.minEmployees.data = template.minEmployees
		form.employees.data = ', '.join([str(emp.external_id) for emp in template.employees])
	if form.validate_on_submit():
		template.name = form.shiftName.data
		template.startTime = form.startTime.data
		template.duration = form.duration.data
		template.maxEmployees = form.maxEmployees.data
		template.minEmployees = form.minEmployees.data

		if form.employees.data:
			empToAdd = form.employees.data.replace(' ', '').split(',')
			for emp in empToAdd:
				if not emp.isdigit():
					flash('Invalid Employee List!', 'danger')
					return redirect(url_for('admin.editTemplate', template_id=template.id))
				employee = User.query.filter_by(external_id=emp).first()
				if not employee:
					flash(f'Employee "{emp}" not found!', 'danger')
					return redirect(url_for('admin.editTemplate', template_id=template.id))
				template.employees.append(employee)
				db.session.commit()
		else:
			template.employees.clear()

		db.session.commit()
		flash('Template Updated!', 'success')
		return redirect(url_for('admin.viewTemplates'))
	return render_template('edit_template.html', form=form, template_id=template_id)

@admin.route('/schedule/configure/template/<int:template_id>/delete', methods=['POST'])
@login_required
def deleteTemplate(template_id):
	template = Template.query.get_or_404(template_id)
	url = url_for('admin.viewTemplates')
	flash(f'Template "{template.name}" Deleted!', 'success')
	db.session.delete(template)
	db.session.commit()
	
	return redirect(url)

skedule/main/routes.py
from flask import render_template, send_from_directory, Blueprint, abort, flash, redirect, request, url_for
from sqlalchemy import and_
from flask_login import login_user, current_user, logout_user, login_required
from skedule import db, bcrypt
from skedule.models import User, Day, Shift, Assignment
from skedule.utils import getLocalizedTime, getWeek, getDayName, daysOfCalendarWeek, ymdToDateTime, oneWeekLater, oneWeekPrior

main = Blueprint('main', __name__)

@main.route('/')
@login_required
def home():
	current_week = getWeek(getLocalizedTime())
	weekdays = [{'name': getDayName(day.weekday()), 'date': day.strftime('%m/%d')} for day in current_week]
	start_date = current_week[0].date()
	end_date = current_week[-1].date()
	
	# Get all days for the week in one query
	days_dict = {day.date: day for day in Day.query.filter(Day.date.between(start_date, end_date)).all()}
	days = [days_dict.get(d.date()) for d in current_week]
	
	# Get all user assignments for the week in one efficient query
	user_assignments = Assignment.query.join(Shift).join(Day).filter(
		Assignment.user_id == current_user.id,
		Day.date.between(start_date, end_date)
	).all()
	
	user_shifts = []
	user_shift_ids = set()
	for ua in user_assignments:
		day_dt = ua.shift.day.date
		user_shift_ids.add(ua.shift.id)
		user_shifts.append({
			'shift': ua.shift,
			'assignment': ua,
			'day_name': getDayName(day_dt.weekday()),
			'date': day_dt.strftime('%m/%d'),
			'time': ua.shift.startTime.strftime('%-I:%M %p')
		})
	
	# Calculate total shifts for the week
	total_shifts = sum(len(day.shifts) if day else 0 for day in days)
	
	return render_template('dashboard.html', time=getLocalizedTime(), weekdays=weekdays, days=days, 
						 user_shifts=user_shifts, user_shift_ids=user_shift_ids, total_shifts=total_shifts)

@main.route('/schedule/shift/<int:shift_id>')
@login_required
def viewShift(shift_id):
	shift = Shift.query.get_or_404(shift_id)
	assignment = Assignment.query.filter_by(shift=shift, user=current_user).first()
	cancellable = False
	requestable = True
	if assignment:
		requestable = False
		if assignment.request == True:
			cancellable = True
	return render_template('shift.html', shift=shift, requestable=requestable, cancellable=cancellable)

@main.route('/schedule/shift/<int:shift_id>/request', methods=['POST'])
@login_required
def requestShift(shift_id):
	shift = Shift.query.get_or_404(shift_id)
	if Assignment.query.filter_by(shift=shift, user=current_user).first():
		flash('You already have a request/assignment for this shift.', 'danger')
	else:
		request = Assignment(user=current_user, shift=shift, confirmed=True, request=True)
		db.session.add(request)
		db.session.commit()
		flash('Shift request submitted.', 'success')
	return redirect(url_for('main.viewShift', shift_id=shift.id))

@main.route('/schedule/shift/<int:shift_id>/remove-request', methods=['POST'])
@login_required
def removeShiftRequest(shift_id):
	shift = Shift.query.get_or_404(shift_id)
	assignment = Assignment.query.filter_by(shift=shift, user=current_user).first()
	if not assignment:
		flash('You do not have a pending request for this shift.', 'danger')
	else:
		db.session.delete(assignment)
		db.session.commit()
		flash('Shift request removed.', 'success')
	return redirect(url_for('main.viewShift', shift_id=shift.id))

@main.route('/schedule')
@login_required
def schedule():
	unavail = False
	inputWeekOf = request.args.get('week')
	highlight = request.args.get('hl')
	if inputWeekOf:
		weekOf = ymdToDateTime(inputWeekOf)
		if not weekOf: abort(404)
		calendarWeek = daysOfCalendarWeek(weekOf)
	else:
		calendarWeek = daysOfCalendarWeek(getLocalizedTime())
	weekOf = calendarWeek[0]
	weekdays = [{'name': getDayName(day.weekday()), 'date': day.strftime('%m/%d')} for day in calendarWeek]
	days = []
	for day in calendarWeek:
		dayRow = Day.query.filter_by(date=day.date()).first()
		if dayRow:
			days.append(dayRow)
		else:
			unavail = True
	return render_template('schedule.html', unavail=unavail, highlight=highlight, weekdays=weekdays, weekOf=weekOf, days=days, owp=oneWeekPrior(weekOf), owl=oneWeekLater(weekOf), hours=[str(i).zfill(4) for i in range(800, 2400, 100)])

@main.route('/upcoming')
@login_required
def upcoming():
	page = request.args.get('page', 1, type=int)
	no_pending = request.args.get('no-pending', False, type=bool)
	per_page = 10
	
	# Get user's upcoming shifts (from today onwards, both confirmed and pending)
	today = getLocalizedTime().date()
	upcoming_assignments = Assignment.query.join(Shift).join(Day).filter(
		and_(Assignment.user_id == current_user.id, Assignment.request == False if no_pending else True),
		Day.date >= today
	).order_by(Shift.startTime.asc()).paginate(
		page=page, per_page=per_page, error_out=False
	)
	
	return render_template('upcoming.html', assignments=upcoming_assignments, no_pending=no_pending)

@main.route('/pending-requests')
@login_required
def pendingRequests():
	page = request.args.get('page', 1, type=int)
	per_page = 10
	
	# Get user's pending requests (request=True)
	pending_assignments = Assignment.query.join(Shift).join(Day).filter(
		and_(Assignment.user_id == current_user.id, Assignment.request == True)
	).order_by(Shift.startTime.asc()).paginate(
		page=page, per_page=per_page, error_out=False
	)
	
	return render_template('pending_requests.html', assignments=pending_assignments)

@main.route('/roster')
@login_required
def roster():
	users = User.query.all()
	return render_template('roster.html', users=users)

@main.route('/static/<path:path>')
def staticFiles(path):
	return send_from_directory('static', path)

skedule/users/routes.py
from flask import render_template, send_from_directory, Blueprint, redirect, url_for, flash, request
from flask_login import login_user, current_user, logout_user, login_required
from skedule import db, bcrypt
from skedule.models import User, Day
from skedule.users.forms import LoginForm, RegisterForm

users = Blueprint('users', __name__)

@users.route('/register', methods=['GET', 'POST'])
def register():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = RegisterForm()
	if form.validate_on_submit():
		hashedpw = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
		user = User(name=form.name.data, email=form.email.data, phone=form.phone.data, password=hashedpw)
		db.session.add(user)
		db.session.commit()
		flash(f'Account created, you may now log in.', 'success')
		return redirect(url_for('users.login'))
	return render_template('register.html', form=form)


@users.route('/login', methods=['GET','POST'])
def login():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = LoginForm()
	if form.validate_on_submit():
		user = User.query.filter_by(email=form.email.data).first()
		if user and bcrypt.check_password_hash(user.password, form.password.data):
			login_user(user, remember=form.remember.data)
			nextpage = request.args.get('next')
			flash(f'Logged in as {user.name} ({user.external_id})', 'success')
			return redirect(nextpage) if nextpage else redirect(url_for('main.home'))
		else:
			flash('Invalid credentials.', 'danger')
	return render_template('login.html', form=form)

@users.route('/logout')
@login_required
def logout():
	logout_user()
	flash('You have been logged out.', 'success')
	return redirect(url_for('users.login'))

skedule/templates/assignment_table.html
{% for assignment in shift.assignments %}
<tr data-assignment-id="{{ assignment.id }}">
  <td class="text-center align-middle">{{ assignment.user.external_id }}{{ assignment.render() }}</td>
  <td class="text-center align-middle">{{ assignment.user.name }}</td>
  <td class="text-center align-middle">{{ assignment.confirmed }}</td>
  <td class="text-center align-middle">{{ not assignment.request }}</td>
  <td class="text-center align-middle">
    <div class="dropend">
      <button type="button" class="btn btn-xs btn-outline-primary dropdown-toggle" href="#" id="dropdownMenuLink" data-bs-toggle="dropdown"><span data-feather="edit-3"></span></button>
      <ul class="dropdown-menu">
        <li><button class="dropdown-item text-success" onclick=""><span data-feather="check"></span> Approve</button></li>
        <li><button class="dropdown-item text-danger" onclick=""><span data-feather="trash-2"></span> Delete</button></li>
        <li><button class="dropdown-item text-primary" onclick=""><span data-feather="user-check"></span> Toggle confirmed</button></li>
      </ul>
    </div>
  </td>
</tr>
{% endfor %}

skedule/templates/login.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <title>Skedule - Login</title>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link href="{{ url_for('static', filename='main.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='auth.css') }}" rel="stylesheet">
  </head>
  
  <body>
    <div class="auth-overlay">
      <div class="auth-modal">
        <div class="auth-header">
          <h1><span class="gold">SKEDULE</span></h1>
          <p class="subtitle">Please sign in to your account.</p>
        </div>
        
        {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
            {% for category, message in messages %}
            <div class='alert alert-{{ category }} alert-dismissible fade show' role='alert'>
              {{ message }} 
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}
          {% endif %}
        {% endwith %}
        
        <form method='POST' action='' id="loginForm">
          {{ form.hidden_tag() }}
          
          <div class="form-floating">
            {% if form.email.errors %}
              {{ form.email(class='form-control is-invalid', maxlength='256', id='emailInput') }}
              <label for="emailInput">Email address</label>
              <div class='invalid-feedback'>
                {% for error in form.email.errors %}
                  {{ error }}
                {% endfor %}
              </div>
            {% else %}
              {{ form.email(class='form-control', maxlength='256', id='emailInput') }}
              <label for="emailInput">Email address</label>
            {% endif %}
          </div>
          
          <div class="form-floating">
            {% if form.password.errors %}
              {{ form.password(class='form-control is-invalid', id='passwordInput', placeholder='Password') }}
              <label for="passwordInput">Password</label>
              <div class='invalid-feedback'>
                {% for error in form.password.errors %}
                  {{ error }}
                {% endfor %}
              </div>
            {% else %}
              {{ form.password(class='form-control', id='passwordInput', placeholder='Password') }}
              <label for="passwordInput">Password</label>
            {% endif %}
          </div>
          
          <div class='form-check'>
            {{ form.remember(class='form-check-input', id='rememberCheck') }}
            {{ form.remember.label(class='form-check-label', for='rememberCheck') }}
          </div>
          
          {{ form.submit(class='btn btn-auth', id='loginButton') }}
          
          <div class="auth-link">
            Don't have an account? <a href="{{url_for('users.register')}}">Sign up here</a>
          </div>
        </form>
      </div>
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="{{ url_for('static', filename='auth.js') }}"></script>
  </body>
</html>

skedule/templates/shift.html
{% extends 'layout.html' %}
{% block content %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
	<h1 class="h2">Shift Details</h1>
	<div class="btn-toolbar mb-2 mb-md-0">
	    <a href="{{ url_for('admin.editShift', shift_id=shift.id) }}" type="button" class="btn btn-sm btn-outline-secondary mb-2">
	      <span data-feather="edit" class="align-text-bottom"></span>
	    </a>
  	</div>
</div>
<div class="d-flex" style='gap: 2rem;'>
	<form method='POST' action='' class='d-flex flex-column px-3 pt-3 pb-3 border bg-light' style='max-width: 27.1rem;'>
	<fieldset class='form-group'>
		<div class='form-group mb-4'>
			<label class="form-control-label mb-2" for="shiftName">Shift Name:</label>			
			<input class="form-control form-control-lg" id="shiftName" name="shiftName" disabled type="text" value="{{shift.name}}">		
		</div>
		<div class="d-flex" style="gap: 1rem;">
			<div class='form-group mb-4'>
				<label class='form-control-label mb-2'>Start Date:</label>
				<small><i>(mm/dd/yyyy)</i></small>
				<input class="form-control form-control-lg" id="startDate" name="startDate" disabled type="text" value="{{shift.startTime.strftime('%m/%d/%Y')}}">
			</div>
			<div class='form-group mb-4'>
				<label class='form-control-label mb-2'>Start Time:</label>
				<small><i>(hhmm)</i></small>
				<input class="form-control form-control-lg" id="startTime" name="startTime" disabled type="text" value="{{shift.startTime.strftime('%H%M')}}">
			</div>
		</div>
		<div class="d-flex justify-content-between" style="gap: 1rem;">
			<div class='form-group mb-4'>
				<label class='form-control-label mb-2'>Duration:</label>
				<small><i>(hhmm)</i></small>
				<input style="max-width: 8rem;" class="form-control form-control-lg" id="duration" name="duration" disabled type="text" value="{{(shift.duration|string).zfill(4)}}">
			</div>
			<div class='form-group mb-4'>
				<label class='form-control-label mb-2'>End Date & Time:</label>
				<small><i>(mm/dd/yyyy, hhmm)</i></small>
				<input class='form-control form-control-lg' disabled id="endTime" value='---'>
			</div>
		</div>
		<div class="d-flex" style="gap: 1rem;">
			<div class='form-group mb-4'>
				<label class='form-control-label mb-2'>Minimum # of Employees:</label>
				<input class="form-control form-control-lg" id="minEmployees" name="minEmployees" disabled type="text" value="{{shift.minEmployees}}">
			</div>
			<div class='form-group mb-4'>
				<label class='form-control-label mb-2'>Maximum # of Employees:</label>
				<input class="form-control form-control-lg" id="maxEmployees" name="maxEmployees" disabled type="text" value="{{shift.maxEmployees}}">
			</div>
		</div>
		<div class='d-flex flex-wrap flex-md-nowrap align-items-center form-group' style='gap: 1rem;'>
			<btn onclick='window.history.back()' class="btn btn-outline-secondary">← Back</btn>
			<a href="{{ url_for('main.schedule', week=shift.startTime.strftime('%Y-%m-%d'), hl=shift.id) }}" class="btn btn-outline-primary">Highlight in Schedule</a>
		</div>
	</fieldset>
	</form>
	{# <div class="vr"></div> #}
	<script type="text/javascript">
	</script>
	<div class="d-flex flex-column" style="gap: 1rem;">
		<div class='d-flex flex-column px-3 pt-3 pb-3 border bg-light align-self-stretch' style='max-width: 18rem;'>
			<h6><label class="form-control-label mb-2">Employees for this shift</label></h6>
			<ul class="list-group mb-2">
			{% if shift.assignments %}
			  {% for assignment in shift.assignments %}
			  <li class="list-group-item" style='overflow-x: scroll; color: {{ assignment.colorize() }};'><b>{{assignment.user.external_id|string}}</b>{{assignment.render()}} {{ assignment.user.name }}</li>
			  {% endfor %}
			{% else %}
				<li class="list-group-item" style='overflow-x: scroll; color: darkgray;'><i>No Employees...</i></li>
			{% endif %}
			</ul>
			{% if requestable %}
			<form action='{{url_for("main.requestShift", shift_id=shift.id)}}' method='POST'>
				<button class="btn btn-outline-success w-100" data-bs-toggle="tooltip" data-bs-placement="right" title="Once your request is approved, the shift will become your responsibility.">Request Shift</button>
			</form>
			{% elif cancellable %}
			<form action='{{url_for("main.removeShiftRequest", shift_id=shift.id)}}' method='POST'>
				<button class="btn btn-outline-danger w-100" data-bs-toggle="tooltip" data-bs-placement="right" title="This will cancel your pending request for this shift.">Cancel Request</button>
			</form>
			{% else %}
				<button class="btn btn-outline-danger w-100" data-bs-toggle="tooltip" data-bs-placement="right" title="This shift is now your responsibility. If you can no longer attend, you must find coverage.">Find Coverage</button>
			{% endif %}
		</div>
		<div class='d-flex flex-column px-3 pt-3 pb-3 border bg-light' style='max-width: 18rem; max-height: 40vh; overflow-y: scroll;'>
			<h6>Employee List key</h6>
			<ul class="list-group mb-2">
				<li class="list-group-item" style='overflow-x: scroll;'><span style="color: #cfc102;">(REQ)</span> = <span>Pending Request</span></li>
				<li class="list-group-item" style='overflow-x: scroll;'><span style="color: #982ff4;">(R)</span> = <span>Ride Along</span></li>
				<li class="list-group-item" style='overflow-x: scroll;'><span style="color: #f19e38;">(T)</span> = <span>Trainee</span></li>
				<li class="list-group-item" style='overflow-x: scroll;'><span style="color: #0000f5;">(A)</span> = <span>Assigned, Yet to Confirm</span></li>
				<li class="list-group-item" style='overflow-x: scroll;'><span style="color: #ea3728;">(C)</span> = <span>Covering</span></li>
				<li class="list-group-item" style='overflow-x: scroll;'><span style="color: #000000;">(P)</span> = <span>Probationary</span></li>
			</ul>
		</div>
	</div>

</div>

{% endblock %}